SZK.HomeManagement/Models/ErrorViewModel.cs
using System;

namespace HomeManagement.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SZK.HomeManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HomeManagement.Models;
using System.Reflection.Metadata;
using SZK.HomeManagement.Shared.Constants;
using Microsoft.VisualBasic;

namespace HomeManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<ShoppingListController> _logger;        

        public HomeController(ILogger<ShoppingListController> logger)
        {
            this._logger = logger;            
        }

        public IActionResult Index()
        {            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SZK.HomeManagement/Controllers/ShoppingListController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HomeManagement.Models;
using System.Net.Http;
using SZK.HomeManagement.Services;
using SZK.HomeManagement.Shared.Models.ProductsServiceModel;
using SZK.HomeManagement.Shared.Constants;

namespace HomeManagement.Controllers
{
    public class ShoppingListController : Controller
    {
        private readonly ILogger<ShoppingListController> _logger;
        private readonly ProductsServiceClient productsServiceClient;

        public ShoppingListController(ILogger<ShoppingListController> logger, ProductsServiceClient productsServiceClient)
        {
            _logger = logger;
            this.productsServiceClient = productsServiceClient;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.ShoppingList = await this.productsServiceClient.GetShoppingListAsync();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> AddNewShoppingListItem(string productCategoryString, string productName, int quantity, string requester, string description, string producer)
        {
            if (!Enum.TryParse(productCategoryString, out ProductCategory productCategory))
            {
                productCategory = ProductCategory.Other;
            }
            ShoppingListItem shoppingListItem = new ShoppingListItem()
            {
                Product = new Product()
                {
                    Name = productName,
                    ProductCategory = productCategory,
                    Producer = producer
                },
                Quantity = quantity,
                Description = description,
                Requester = requester,
                RequestedOn = DateTime.Now
            };

            await this.productsServiceClient.AddShoppingListItem(shoppingListItem);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveItemFromList(int id)
        {            
            await this.productsServiceClient.RemoveItemFromList(id);
            return RedirectToAction("Index");
        }
    }
}

SZK.HomeManagement/Views/Home/Index.cshtml
@{       
    @using SZK.HomeManagement.Shared.Constants;
    ViewData[ViewConstants.Keys.Title] = "Strona główna";
}

<div class="text-center">
    <h1 class="display-4">@ViewData[ViewConstants.Keys.Title]</h1>
    <p>Tbd soon...</p>
</div>

SZK.HomeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="~/css/mycss.min.css" rel="stylesheet" />



    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">

        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <i class="fas fa-home"></i>
            Home Management
        </a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                            <div class="sb-nav-link-icon"></div>
                            Strona główna
                        </a>
                        <a class="nav-link" asp-area="" asp-controller="ShoppingList" asp-action="Index">
                            <div class="sb-nav-link-icon"></div>
                            Lista zakupów
                        </a>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <div class="container-fluid">
                <main role="main">
                    @RenderBody()
                </main>
            </div>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2020</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/myjs.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SZK.HomeManagement/Views/ShoppingList/Index.cshtml
@{
    ViewData[ViewConstants.Keys.Title] = "Lista zakupów";
}


<div class="text-center">
    <h1 class="display-4">@ViewData[ViewConstants.Keys.Title]</h1>
    <div class="row">
        @foreach (ShoppingListItem element in ViewBag.ShoppingList)
        {
            <div class="col-xl-3 col-md-6">
                <form action="ShoppingList/RemoveItemFromList" method="delete">
                    <div class="card bg-primary text-white mb-4">
                        <div class="card-header">
                            <div class="form-group">
                                <input hidden class="form-control" type="number" name="id" value="@element.ShoppingListItemId" />
                            </div>
                            Kategoria: @element.Product.ProductCategory
                        </div>
                        <div class="card-body">
                            <p>
                                Produkt: @element.Product.Name <br />
                            </p>
                            <p>
                                Ilość: @element.Quantity
                            </p>
                            Producent: @(string.IsNullOrEmpty(element.Product.Producer) ? "Dowolny" : element.Product.Producer)<br />
                            Szczegóły: @element.Description
                            Dodano: @element.RequestedOn <br />
                            Autor: @element.Requester
                        </div>
                        <div class="card-footer small-text-white">
                            <div class="form-group">
                                <input type="submit" value="Kupione" class="form-control" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        }
        <div class="col-xl-3 col-md-6">
            <form action="ShoppingList/AddNewShoppingListItem" method="post">
                <div class="card bg-primary text-white mb-4">
                    <div class="card-header">
                        Dodaj produkt
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <input hidden class="form-control" type="number" />
                        </div>
                        <div class="form-group">
                            <select class="form-control" name="productCategoryString">
                                <option selected value="@ProductCategory.Dairy">Nabiał</option>
                                <option value="@ProductCategory.Fat">Tłuszcze</option>
                                <option value="@ProductCategory.Fruit">Owoce</option>
                                <option value="@ProductCategory.Vegetable">Warzywa</option>
                                <option value="@ProductCategory.Grain">Produkty zbożowe</option>
                                <option value="@ProductCategory.Meat">Mięso</option>
                                <option value="@ProductCategory.Drink">Napoje</option>
                                <option value="@ProductCategory.Other">Inne</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="text" placeholder="Nazwa produktu" name="productName" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="number" placeholder="Ilość" name="quantity" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="text" placeholder="Szczegóły" name="description" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="text" placeholder="Producent" name="producer" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="text" placeholder="Autor" name="requester" />
                        </div>
                    </div>
                    <div class="card-footer small-text-white">
                        <div class="form-group">
                            <input type="submit" value="Dodaj" class="form-control" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>